export const properties = [
  {
    id: "1",
    name: "The Manhattan Loft",
    location: "New York City, NY",
    price: 285,
    image: "/luxury-modern-loft-apartment-with-city-view.jpg",
    amenities: ["wifi", "ac", "kitchen", "parking"],
    description:
      "Experience the pulse of the city from this stunning Manhattan loft. Floor-to-ceiling windows offer breathtaking skyline views, while the open-concept design provides the perfect blend of space and style. Premium finishes throughout make this the ultimate urban retreat.",
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    images: [
      "/luxury-loft-living-room-with-city-view.jpg",
      "/modern-kitchen-with-marble-counters.jpg",
      "/elegant-master-bedroom-with-view.jpg",
      "/spa-style-bathroom-luxury.jpg",
    ],
  },
  {
    id: "2",
    name: "Lakeside Penthouse",
    location: "Chicago, IL",
    price: 320,
    image: "/penthouse-apartment-lakefront-view-luxury.jpg",
    amenities: ["wifi", "ac", "kitchen"],
    description:
      "Perched high above the magnificent mile, this penthouse offers unparalleled views of Lake Michigan. The sophisticated interior features designer furnishings, a chef's kitchen, and a private terrace perfect for sunset cocktails.",
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    images: [
      "/penthouse-living-room-lake-view.jpg",
      "/designer-kitchen-modern-luxury.jpg",
      "/lakeview-bedroom.png",
      "/private-terrace-city-penthouse.jpg",
    ],
  },
  {
    id: "3",
    name: "SoMa Designer Suite",
    location: "San Francisco, CA",
    price: 275,
    image: "/modern-designer-apartment-san-francisco.jpg",
    amenities: ["wifi", "ac", "kitchen", "parking"],
    description:
      "Located in the heart of San Francisco's tech district, this designer suite combines industrial charm with modern luxury. Exposed brick walls, curated art, and smart home features create an inspiring space for work or leisure.",
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    images: [
      "/industrial-modern-living-room.jpg",
      "/minimalist-bedroom-design.jpg",
      "/modern-bathroom-with-rainfall-shower.jpg",
      "/home-office-space-modern.jpg",
    ],
  },
  {
    id: "4",
    name: "Art Deco Residence",
    location: "Miami Beach, FL",
    price: 340,
    image: "/art-deco-luxury-apartment-miami-beach.jpg",
    amenities: ["wifi", "ac", "kitchen", "parking"],
    description:
      "Step into the glamour of Miami's iconic Art Deco district. This meticulously restored residence features period details, tropical views, and direct beach access. The perfect blend of vintage charm and modern comfort.",
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    images: [
      "/art-deco-living-room-ocean-view.jpg",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
  },
  {
    id: "5",
    name: "Capitol Hill Townhouse",
    location: "Washington, D.C.",
    price: 295,
    image: "/placeholder.svg?height=600&width=800",
    amenities: ["wifi", "ac", "kitchen"],
    description:
      "A beautifully renovated historic townhouse steps from the Capitol. Original hardwood floors and ornate moldings meet contemporary amenities. The private garden and rooftop deck offer peaceful retreats in the heart of the nation's capital.",
    bedrooms: 3,
    bathrooms: 2,
    guests: 5,
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
  },
  {
    id: "6",
    name: "Downtown Seattle Studio",
    location: "Seattle, WA",
    price: 195,
    image: "/placeholder.svg?height=600&width=800",
    amenities: ["wifi", "ac", "kitchen", "parking"],
    description:
      "A sleek urban studio in the heart of downtown Seattle. Enjoy views of the Space Needle, walk to Pike Place Market, and experience the city's vibrant culture. Perfect for solo travelers or couples seeking an urban adventure.",
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
  },
]
